config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :messages
  resources :abouts
  resources :sliders

  resources :albums do
    resources :photos do
      get 'set_cover', on: :member
    end  
  end
  resources :categories do
    resources :options
  end
  root to: 'sliders#index'
  resources :users
  get 'signup'  => 'users#new'
  get '/login' => 'sessions#new'  
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy' 
 
  

  

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :options
  mount_uploader :image, ImageUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/information.rb
class Information < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :category
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  mount_uploader :avatar, AvatarUploader
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  mount_uploader :slide, SlideUploader
  NUMBERS = (0..3).to_a
  validates :number, inclusion: NUMBERS
end

app/models/user.rb
class User < ActiveRecord::Base
  after_destroy :ensure_an_admin_remains
  has_secure_password

  ROLES = %w[user editor admin]
  before_create do
    if User.first.nil?
      self.role = 'admin'
    end
  end

  def editor? 
    self.role == 'editor' || 'admin' 
  end

  def admin? 
    self.role == 'admin' 
  end



  private
    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end  
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  before_action :require_editor, only: [:new, :create, :edit, :update]
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]
  def index
    @categories = Category.all
    @albums = Album.all
  end

  def show
    @categories = Category.all
  end

  def new
    @categories = Category.all
    @album = Album.new
  end

  def edit
    @categories = Category.all
    @album = Album.find(params[:id])
  end

  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      #@album = Album.find(params[:id])
      @album = AlbumDecorator.decorate(Album.find(params[:id]))
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :image)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Название<br>
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    Обложка альбома<br>
    <%= f.text_field :image %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> 

app/views/albums/edit.html.erb
<div class="container">
  <h4>Добавить картинку</h4>
    <%= form_for([@album, @album.photos.build]) do |f| %> 
      <%= f.file_field :avatar  %>  
      <%= f.hidden_field :album_id %><br/>
      <%= f.submit 'Create Image', :class => 'btn btn-sm btn-primary' %>
    <% end %>
  <br/>
  <%= render 'form' %>





    <%= link_to 'Назад', @album %> |
    <%= link_to 'Все альбомы', albums_path(@album) %>
  </div>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h3 class="text-center">Альбомы</h3>

  <% @albums.each do |album| %>
    <div class="col-md-4 thumbnail">
        <%= link_to album.title, album_path(album) %><br/>
        <%= link_to image_tag(album.image, class: "ex1"), album %><br/>
        
        <% if current_user && (current_user.editor? || current_user.admin?) %> 
          
          <%= link_to 'Edit', edit_album_path(album) %>
          <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %>
       <% end %>
    </div> 
    <% end %>


<br/>
<% if current_user && (current_user.editor? || current_user.admin?) %> 
  <%= link_to 'New Album', new_album_path %>
<% end %>
</div>

app/views/albums/new.html.erb
 <%= render 'form' %>

app/views/albums/show.html.erb
<div class="container">
  <h3 class="text-center"><%= @album.title %></h3>
  <p>Обложка: <%= @album.cover.id if @album.cover? %></p>
 <% if current_user && (current_user.editor? || current_user.admin?) %> 
    <%= link_to 'Редактировать', edit_album_path(@album) %> |
<% end %>
    <%= link_to 'Назад', albums_path %><br/>
  <p class="text-center" id="notice"><%= notice %></p>
    <% @album.photos.each do |photo| %>
      <div class="col-lg-2 col-md-2 col-xs-6 thumb">
        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="<%= photo.avatar %>" data-target="#image-gallery">
          <img class="img-responsive"  src="<%= photo.avatar %>" alt="">
        </a>
      </div>
    <% end %>
    <br/>

   

 <% @album.photos.each do |photo| %>

<div class="modal" id="image-gallery" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="image-gallery-title"></h4>
            </div>
            <div class="modal-body">
                <img id="image-gallery-image" class="img-responsive" src="<%= photo.avatar %>">
            </div>
            <div class="modal-footer">

                <div class="col-md-2">
                    <button type="button" class="btn btn-primary" id="show-previous-image">Previous</button>
                </div>

                <div class="col-md-8 text-justify" id="image-gallery-caption">
                
                </div>

                <div class="col-md-2">
                    <button type="button" id="show-next-image" class="btn btn-default">Next</button>
                </div>
            </div>
        </div>
    </div>
</div>
<% end %>

<hr/>
<hr/>
<hr/>

<ul>
  <% @album.photos.each do |photo| %>
    <li><%= photo.id %> -- <%=  photo.avatar %> -- <%= link_to "сделать обложкой", set_cover_album_photo_path(photo.album_id, photo) %></li>
  <% end %>
</ul>