config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :messages
  resources :abouts
  resources :sliders

  resources :albums do
    resources :photos do
      get 'set_cover', on: :member
    end  
  end
  resources :categories do
    resources :options
  end
  root to: 'sliders#index'
  resources :users
  get 'signup'  => 'users#new'
  get '/login' => 'sessions#new'  
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy' 
 
  

  

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :options
  mount_uploader :image, ImageUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/information.rb
class Information < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :category
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  mount_uploader :avatar, AvatarUploader
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  mount_uploader :slide, SlideUploader
  NUMBERS = (0..3).to_a
  validates :number, inclusion: NUMBERS
end

app/models/user.rb
class User < ActiveRecord::Base
  after_destroy :ensure_an_admin_remains
  has_secure_password

  ROLES = %w[user editor admin]
  before_create do
    if User.first.nil?
      self.role = 'admin'
    end
  end

  def editor? 
    self.role == 'editor' || 'admin' 
  end

  def admin? 
    self.role == 'admin' 
  end



  private
    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  #before_action :require_user, only: [:index, :show]
  before_action :require_editor, only: [:new, :create, :edit, :update]
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]
  def index
    @categories = Category.all
  end

  def show 
    @categories = Category.all
    @category = Category.find(params[:id])
    @options = @category.options
    
  end

  def new
    @categories = Category.all
    @category = Category.new
  end

  def edit
    @categories = Category.all
    @category = Category.find(params[:id])
    #redirect_to posts_path unless current_user == @post.user
  end

  def create
    @category = Category.new(category_params)
    
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:article, :title, :quantity, :price, :image)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :article %><br>
    <%= f.text_field :article %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <h3>Editing Category</h3>
    <%= render 'form' %>
  

    <%= link_to 'Show', @category %> |
    <%= link_to 'Back', categories_path %>
</div>

 

app/views/categories/index.html.erb
<div class="container">
  <% @categories.each do |category| %>
    <div class="col-md-3 col-sm-6 col-xs-12 ">    
      <a href='/categories/<%= category.id %>'><%= image_tag(category.image, class: "ex img-rounded") %></a><br/>

        <% if current_user && (current_user.editor? || current_user.admin?) %> 
          <%= link_to 'Edit', edit_category_path(category) %>
        <% end %>

        <% if current_user && current_user.admin? %> 
          <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>

    </div>
     
  <% end %>
        <% if current_user && current_user.admin? %> 
  <%= link_to 'Добавить категорию меню', new_category_path %>
   <% end %>
</div>
    

app/views/categories/new.html.erb
<div class="container">
  <h3>New Category</h3>
  <%= render 'form' %>
  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<div class="container">  
  <h3 class="text-center"><%= @category.article %></h3>
  <div class="text-center">
    <img class="image1" src="/assets/podnos3.png">
  </div>
  <table class="table">
    <thead>
      <tr>
        <th class="size text-center col-md-8"><%= @category.title %></th>
        <th class="col-md-2"><%= @category.quantity %></th>
        <th class="col-md-1"><%= @category.price %></th>
        <% if current_user && (current_user.editor? || current_user.admin?) %> 
          <th class="col-md-1">Действие</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @category.options.each do |option| %>
        <tr>
          <td class="text-center"><b><%= option.title %></b></td>
          <td><b><%= option.quantity %></b></td>
          <td><b><%= number_to_currency(option.price, unit: "", separator: ",", delimiter: "") %></b></td>          
          <td>
            <% if current_user && (current_user.editor? || current_user.admin?) %> 
              <%= link_to 'Редактировать', edit_category_option_path(@category, option) %>
              <%= link_to 'Удалить', [@category, option], method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br/>
  <% if current_user && (current_user.editor? || current_user.admin?) %> 
    <%= form_for([@category, @category.options.build]) do |f| %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Название блюда(описание)' %>
    <%= f.text_field :quantity, class: 'form-control', placeholder: 'Количество(г,мл), формат(000/000/000)' %>
    <%= f.text_field :price, class: 'form-control', placeholder: 'Цена' %>
    <%= f.submit 'Добавить в меню', class: 'btn btn-success' %></td>
   
    <% end %>

  <%= link_to 'Edit', edit_category_path(@category) %> |
  <%= link_to 'Destroy', @category, method: :delete, data: { confirm: 'Are you sure?' } %> |
  
  <% end %>

  <%= link_to 'Back', categories_path %>
</div>
     