config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :messages
  resources :abouts
  resources :sliders

  resources :albums do
    resources :photos do
      get 'set_cover', on: :member
    end  
  end
  resources :categories do
    resources :options
  end
  root to: 'sliders#index'
  resources :users
  get 'signup'  => 'users#new'
  get '/login' => 'sessions#new'  
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy' 
 
  

  

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :options
  mount_uploader :image, ImageUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/information.rb
class Information < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :category
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  mount_uploader :avatar, AvatarUploader
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  mount_uploader :slide, SlideUploader
  NUMBERS = (0..3).to_a
  validates :number, inclusion: NUMBERS
end

app/models/user.rb
class User < ActiveRecord::Base
  after_destroy :ensure_an_admin_remains
  has_secure_password

  ROLES = %w[user editor admin]
  before_create do
    if User.first.nil?
      self.role = 'admin'
    end
  end

  def editor? 
    self.role == 'editor' || 'admin' 
  end

  def admin? 
    self.role == 'admin' 
  end



  private
    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end  
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Restoran</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

    <!-- Bootstrap -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-latest.min.js"></script>
    <script src="//unslider.com/unslider.js"></script>
  </head>
  <body>
  <nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">       
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Меню<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Все меню', categories_path(@category) %></li>
            <% @categories.each do |category| %>
              <li>
                <%= link_to category.title, category_path(category) %>
              </li>
            <% end %>
          </ul>
        </li>
        <li><%= link_to "О нас", abouts_path(@about) %></li>
        <li><%= link_to "Новости", messages_path(@message) %></li>
        <li><%= link_to "Галерея", albums_path(@album) %></li>
        <li><%= link_to "Отзывы", reviews_path(@review) %></li>
        <li><%= link_to "Добавить Сайды", sliders_path(@slider) %></li>
        
      </ul>
     
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %> 
  
    <li><a><%= current_user.email %></a></li> 
    <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
  
<% else %> 
 
    <li><%= link_to "Login", 'login' %></li> 
    <li><%= link_to "Signup", 'signup' %></li> 
  
<% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <%= yield %>
<footer class="container">heeloo</footer> 
    
  </body>
</html>